### PR TITLE
Properly working slide window animation for Android and hinttext property for ios

### PR DESCRIPTION
**Pull request by hardikamal**

### CODE REVIEW

**Comment by jasonkneen** [comment]
Noticed the addition of createtextfield method which adds events in the commonJS file. Have you tested this in instruments to ensure its being released properly when windows are closed?

I suspect it's not as the event handlers are being added on the commonJS side. In past experience I've found that unless this is explicitly removed the textfield will not be destroyed and will keep its parent window open. 

Worth testing.

**Comment by FokkeZB** [comment]
@jasonkneen I agree this should be tested, though I see no external references in the listeners so they should be good.

@hardikamal what do you mean when you say that hintText *sometimes* doesn't work on iOS?

@hardikamal I'd like the custom animations in a `platform/android/res/anim` subfolder and please leave the defaults as they were and explain how people can use the custom ones using the options dictionary.

**Comment by hardikamal** [comment]
@FokkeZB HintText property has not been working for me on my simulator so had to create that...

@FokkeZB The default animation is only available to slide from right to left and there is no default animation provided to slide from left to right on back press so using custom animation left to right can be achieved...

**Comment by FokkeZB** [comment]
@hardikamal you closed the issue. Does this mean you don't want to go on with this?

**Comment by nuno** [comment]
@FokkeZB I was asked the same, can you provide some example for what you want accomplished @hardikamal ?

**Pull request closed without merging**
